services:
  - type: web
    name: shrutilipi-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: FRONTEND_URL
        value: https://frontend-six-woad-540yl4bn2c.vercel.app
